"""empty message

Revision ID: 1ef82ba45a6e
Revises: 0335105668e3
Create Date: 2023-02-12 09:43:46.120944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ef82ba45a6e'
down_revision = '0335105668e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calorie_intake', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('fat', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('protein', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('carbohydrates', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('sodium', sa.Float(), nullable=False))
        batch_op.alter_column('food',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('date_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calorie_intake', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('food',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('sodium')
        batch_op.drop_column('carbohydrates')
        batch_op.drop_column('protein')
        batch_op.drop_column('fat')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
