"""empty message

Revision ID: 2a940b68f529
Revises: fecea675554c
Create Date: 2023-02-17 18:41:24.463157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a940b68f529'
down_revision = 'fecea675554c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calorie_intake', schema=None) as batch_op:
        batch_op.drop_column('sodium')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calorie_intake', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sodium', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
